manageUsers/urls.py
from django.urls import path

from .views import viewRegister, logIn, close_session

urlpatterns = [
    path('register', viewRegister.as_view(), name="Register"),
    path('login', logIn, name="Login"),
    path('closesess', close_session, name="CloseSession"),
]

predictionsapp/urls.py
from django.urls import path

from .views import classifier

urlpatterns = [
    
    path('classifier', classifier, name="Classifier"),
]

venomClassifier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('venomClassifierApp.urls')),
    
    path('', include('manageUsers.urls')),

    path('', include('predictionsapp.urls')),
]

venomClassifierApp/urls.py
from django.urls import path

from venomClassifierApp import views

urlpatterns = [   
    path('',views.home, name="Home"),
]

manageUsers/models.py
from django.db import models

# Create your models here.

predictionsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

class Sequences(models.Model):
    sequence=models.TextField(max_length=600)
    prediction=models.CharField(max_length=1)
    probnotvenom=models.FloatField(default=0.0)
    probvenom=models.FloatField(default=0.0)
    # fasta_file = models.FileField(default='default.fasta', blank=True, validators=[FileExtensionValidator(allowed_extensions=['fasta'])])
    date=models.DateTimeField(auto_now_add=True)
    consultant=models.ForeignKey(User, default=None, on_delete=models.PROTECT)

venomClassifierApp/models.py
from django.db import models

# Create your models here.

predictionsapp/forms.py
from django import forms
from . import models

class sequenceForm(forms.ModelForm):
    class Meta:
        model = models.Sequences
        fields = ['sequence',]

manageUsers/views.py
from dataclasses import dataclass
from django.shortcuts import redirect, render
from django.views.generic import View
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class viewRegister(View):
    
    def get(self, request):
        form=UserCreationForm()
        return render(request, "manageUsers/register.html", {"form":form})

    def post(self, request):
        form=UserCreationForm(request.POST)

        if form.is_valid():
            user=form.save()
            login(request, user)
            
            return redirect('Home')

        else:
            for msg in form.error_messages:
                messages.error(request, form.error_messages[msg])
            
            return render(request, "manageUsers/register.html", {"form":form})


def close_session(request):
    logout(request)

    return redirect('Home')

def logIn(request):
    if request.method=="POST":
        form=AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user_name=form.cleaned_data.get("username")
            pasw=form.cleaned_data.get("password")

            user=authenticate(username=user_name, password=pasw)

            if user is not None:
                login(request, user)
                return redirect('Home')
            else:
                messages.error(request, "Username or Password incorrect")
        else:
            messages.error(request, "Incorrect Username or Password")

    form=AuthenticationForm()
    return render(request, "manageUsers/login.html", {"form":form})

predictionsapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import forms

import pandas as pd
import numpy as np
from Bio import SeqIO

from keras import preprocessing
from keras.models import load_model
from keras_preprocessing.text import tokenizer_from_json
from venomClassifier import settings
import json 
from os.path import join
from django.contrib.auth.models import User
from .models import Sequences

MAX_LENGHT = 600

@login_required(login_url='Login')
def classifier(request):
    if request.method=='POST':
        form = forms.sequenceForm(request.POST)
        if form.is_valid():
            if request.FILES:
                try:
                    meta=[]
                    sequence=[]
                    for seq_record in SeqIO.parse(request.FILES, "fasta"):
                        meta.append(str(seq_record.description))
                        sequence.append(str(seq_record.seq))
                    df = pd.DataFrame(data ={'Meta':meta,'Sequence':sequence})
                    df['Clasification'] = ''
                    
                    X = np.array(df['Sequence'].tolist())
                except:
                    form = forms.sequenceForm()

                    return render(request, 'predictionsapp/classifier.html', { 'form': form })
            else:
                X = []
                seq = (request.POST)['sequence']
                X.append(seq.upper())
                
            
            with open(join(settings.BASE_DIR, 'predictionsapp/model_config/tokenizer.json')) as f:
                data = json.load(f)
                tokenizer = tokenizer_from_json(data)

            X = tokenizer.texts_to_sequences(X)
            X = preprocessing.sequence.pad_sequences(X, maxlen=MAX_LENGHT, padding='post')
            
            loading_path = join(settings.BASE_DIR, 'predictionsapp/model_config/venom_classifier_model1.h5')
            model = load_model(loading_path)

            predictions = model.predict(x=X, verbose=0)
            rounded_pred = np.argmax(predictions, axis=-1)

            for i in range(len(predictions)):
                prbNotVenom=predictions[i][0]
                prbVenom=predictions[i][1]

                instance = form.save(commit=False)
                instance.probnotvenom = round((prbNotVenom * 100),2)
                instance.probvenom = round((prbVenom * 100),2)
                instance.consultant = request.user
                instance.prediction=rounded_pred[i]
                
                instance.save()

            form=forms.sequenceForm()
        else:
            logUser = (request.user).id
            # instance=[]
            # for i in Sequences.objects.get(consultant_id = logUser):
            #     instance.append(i)
            for instance in Sequences.objects.raw("SELECT ps.id FROM predictionsapp_sequences as ps WHERE consultant_id = {0} ORDER BY date DESC".format(logUser)):
                instance.delete()
            


    else:
        form = forms.sequenceForm()


    logUser = (request.user).id
    predictionsList=[]
    for i in Sequences.objects.raw("SELECT ps.id, ps.sequence, ps.prediction, ps.probnotvenom, ps.probvenom FROM predictionsapp_sequences as ps WHERE consultant_id = {0} ORDER BY date DESC".format(logUser)):
        predictionsList.append(i)
    
    for i in range(len(predictionsList)):
        if len(predictionsList[i].sequence) > 15:
            predictionsList[i].sequence = predictionsList[i].sequence[:15] + '...'
    
    ctx = {'form': form, 'predictionList':predictionsList}

    return render(request, 'predictionsapp/classifier.html', ctx)

venomClassifierApp/views.py
from django.shortcuts import render


def home(request):

   return render(request, "venomClassifierApp/home.html")

manageUsers/templates/manageUsers/login.html
{% extends "venomClassifierApp/__base.html" %}

{% block title %} Log In {% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<form method="post" action=""> {% csrf_token %}
    <div class="inset">
        {% if messages %}

            {% for msg in messages %}

                <span class="alert alert-{{msg.tags}}" style="padding-bottom: 5px; padding-top: 5px;"> {{msg}} </span>    

            {% endfor %}

        {% endif %}
        <br>
        {{form|crispy}}
    </div>
    <p class="p-cont">
        <a href="{% url 'Register' %}">Sign Up</a>
        <input type="submit" name="go" id="go" value="Sign In">
    </p>
</form>


{% endblock %}

manageUsers/templates/manageUsers/register.html
{% extends "venomClassifierApp/__base.html" %}

{% block title %} Sign Up {% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<form method="post" action=""> {% csrf_token %}
    <div class="inset">
        {{form|crispy}}
    </div>
    <p class="p-cont">
        <a href="{% url 'Login' %}">Sign In</a>
        <input type="submit" name="go" id="go" value="Sign Up">
    </p>
</form>


{% endblock %}

predictionsapp/templates/predictionsapp/classifier.html
{% extends "venomClassifierApp/__base.html" %}

{% block title %} Clasifica tus secuencias {% endblock %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" href="{% static 'css/estilos.css' %}">

    <!--/#main-nav-->
    <main>
        <div id="clasificator" class="parallax">
            <div style="text-align:center;">
                <div id ="Help" style="text-align: left;">
                    <nav id ="menuu">
                       <ul>
                            <li>
                                <br><a href="#"><img src="{% static 'images/help.ico' %}" style="height: 4vh;"></a>
                                <ul>
                                    <li>
                                        <p class="desp">
                                            VenomClassifier only supports protein chains with a size less than or equal to 600 chars.
                                        </p>
                                        <p class="desp">Dictionary of amino acid abbreviations:</p>
                                        <img src="{% static 'images/Abreviaciones.jpg' %}">
                                    </li>
                                </ul>
                            </li>
                        </ul> 
                    </nav>
                </div>
            </div>
            <div class="container ">
                <div class="heading wow fadeInDown animated" data-wow-duration="1000ms" data-wow-delay="300ms">
                </div>
                <div class="heading wow fadeInDown animated" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <div class="row">
                        <form method="post" action=""> {% csrf_token %}
                            <div class="text-center col-sm-8 col-sm-offset-2">
                                <h2><strong>Write your sequence</strong></h2>
                                <div class="parallax_b">
                                    <strong>
                                        {{ form.sequence }}
                                </strong>
                                </div>
                            </div>
                            <div class="row">
                                <div class="text-center col-sm-8 col-sm-offset-2">
                                    <br>
                                    <input type="submit" class="btn btn-lg btn-primary" value="Predict">
                                </div>
                            </div>
                            <div class="row">
                        </form>

                    </div>
                        <br>
                        <link rel="stylesheet" href="{% static 'css/stickytable.css' %}">
                        <div class="text-center col-sm-8 col-sm-offset-2 view">
                            <h2><strong>Results</strong></h2>
                            <!-- <div class="parallax_b" style="display: flex; justify-content: center;"> -->
                                <table border=2 style="border-color: white; background-color: aliceblue; opacity: .7;">
                                    <thead class="predTableRow">
                                        <th class="predTableCol sticky-col sticky-col first-col">Prediction</th>
                                        <th class="predTableCol">Not-Venom %</th>
                                        <th class="predTableCol">Venom %</th>
                                        <th class="predTableCol">Sequence</th>
                                    </thead>

                                    {% for pred in predictionList %}
                                        <tr class="predTableRow">
                                            <td class="predTableCol sticky-col first-col">{{pred.prediction}}</td>
                                            <td class="predTableCol">{{pred.probnotvenom}}%</td>
                                            <td class="predTableCol">{{pred.probvenom}}%</td>
                                            <td  class="predTableCol" style="text-transform: uppercase; text-align: left">{{pred.sequence}}</td>
                                        </tr>
                                    {% endfor %}

                                </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="text-center col-sm-8 col-sm-offset-2">
                            <br>
                            <form method="post" action=""> {% csrf_token %}
                                <input type="submit" class="btn btn-lg btn-primary" value="Clear">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    
    <!--#footer-->
    <footer id="footer">
        <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
          <div class="container text-center">
            <div class="footer-logo">
              <a href="{% url 'Home' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}" alt=""></a>
            </div>

          </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
            $(document).ready(function(){
                $('textarea[name="sequence"]').keypress(function (e) {
                    $("#error_msg").html("");
                    var key = e.keyCode;
                    $return = (key == 8 || (key > 64 && key < 91) || (key > 96 && key < 123));
                    if(!$return) {
                    $("#error_msg").html("No special characters Please!");
                    return false;
                    }
                });
            });
    </script>
    <style>
        #id_sequence {
            display: block;
            width: 100%;
            background-color: aliceblue; 
            opacity: .7; 
            text-transform: uppercase;
            min-height: 180px;
            resize: none;
            font-weight: 300;
            color: rgb(0, 0, 0);
            height: auto;
            border-color: rgba(255,255,255,.1);
            border-radius: 0;
            box-shadow: none;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            background-image: none;
            border: 1px solid #ccc;
            font-family: inherit;
            overflow: auto;
        }
    </style>
{% endblock %}

venomClassifierApp/templates/venomClassifierApp/__base.html
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Clasificador de Veneno Online">
        <meta name="author" content="">
        <title>
            {% block title %} {% endblock %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link id="css-preset" rel="stylesheet" href="{% static 'css/preset.css' %}">
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">


        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    </head>
    <body>
        <div class="main-nav">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'Home' %}">
                  <h1><img class="img-responsive" src="{% static 'images/logo.png' %}" alt="logo"></h1>
                </a>                    
              </div>
              <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">                 
                  <li class="scroll active"><a href="{% url 'Home' %}">Home</a></li>
                  {% if user.is_authenticated%}
                    <li style="display: block; color: white; text-align: center; padding-top: 15px; padding-left: 15px; padding-right: 15px; font-size: 16px; font-family: 'Open Sans', sans-serif;">
                      Hello <br>{{ user.username }}</li>
                    <li><a href="{% url 'CloseSession' %}">Sign Out</a></li>
                  {% else %}
                    <li><a href="{% url 'Login' %}">Sign In</a></li>
                    <li><a href="{% url 'Register' %}">Sign Up</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
        </div><!--/#main-nav-->
        {% block content %}

        {% endblock %}
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.inview.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/mousescroll.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lightbox.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    </body>
</html>

venomClassifierApp/templates/venomClassifierApp/home.html
{% extends "venomClassifierApp/__base.html" %}

{% block title %} Bienvenido {% endblock %}

{% block content %}
  <!--.preloader-->
  <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
  <!--/.preloader-->
  {% load static %}
  <header id="home">
    <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        <div class="item active" style="background-image: url(https://cdn.pixabay.com/photo/2014/11/23/21/22/snake-543243_960_720.jpg)">
          <div class="caption">
            <h1 class="animated fadeInLeftBig">Bienvenido a nuestro <br><span>Clasificador de venenos</span></h1>
            <p class="animated fadeInRightBig">clasificador por proteinas</p>
            <a data-scroll class="btn btn-start animated fadeInUpBig" href="{% url 'Classifier' %}">Empieza a clasificar</a>
          </div>
        </div>
        
        <div class="item" style="background-image: url(https://cdn.pixabay.com/photo/2015/10/22/18/38/scorpion-1001742_960_720.jpg)">
          <div class="caption">
            <h1 class="animated fadeInLeftBig">Bienvenido a nuestro <br><span>Clasificador de venenos</span></h1>
            <p class="animated fadeInRightBig">clasificador por proteinas</p>
            <a data-scroll class="btn btn-start animated fadeInUpBig" href="{% url 'Classifier' %}">Empieza a clasificar</a>
          </div>
      </div>
      <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left center"></i></a>
      <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right center"></i></a>

      <a id="tohash" href="#services"><i class="fa fa-angle-down"></i></a>

    </div><!--/#home-slider-->
    
  </header><!--/#home-->
  
  <section id="services">
    <div class="container">
      <div class="heading wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
        <div class="row">
          <div class="text-center col-sm-8 col-sm-offset-2">
            <h2>Sobre el clasificador</h2>
            <p>El desarrollo de Machine Learning es utilizado para la identificación de patrones dentro de una serie de datos. En este caso se planea ejecutar un modelo de Machine Learning que a partir de los datos proporcionados dentro de las bases de datos con información de venenos, desarrollar una aplicación que permita una fácil interacción entre científico-máquina para la identificación de venenos a partir de una cadena de caracteres, que serán una cadena de proteínas o transcriptomas.</p>
          </div>
        </div> 
      </div>
      <div class="heading wow fadeInUp">
        <div class="row">
          <div class="text-center col-sm-4 col-sm-offset-1">
            <p>En el campo de la biología molecular, existe una rama llamada venómica, que son los estudios de proteómica de venenos. Esta rama se ha revelado como una estrategia adecuada para identiﬁcar y cuantiﬁcar las familias de toxinas presentes en los venenos.</p>
          </div>
          <div class="text-center col-sm-5 col-sm-offset-1">
            <img src="https://cdn.pixabay.com/photo/2021/02/13/09/43/brain-6010961_960_720.jpg" alt="machine learning" style="width: 40vw;">
          </div>
        </div> 
      </div>
    </div>
  </section>

  <footer id="footer">
    <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
      <div class="container text-center">
        <div class="footer-logo">
          <a href="{% url 'Home' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}" alt=""></a>
        </div>
      </div>
    </div>
  </footer>

{% endblock %}